### PR TITLE
Replace python 3.8 in unit tests matrix with python 3.11

### PR DESCRIPTION
**Pull request by liamhuber**
The latest version of numpy (1.25) dropped 3.8 support. Let's also ditch it and add 3.11 to the tests.

### CODE REVIEW

**Comment by liamhuber** [comment]
[Pointing pyiron_contrib to this branch got the 3.11 tests running A-OK](https://github.com/pyiron/pyiron_contrib/pull/731), so IMO this is ready to go. I'll leave it up for a couple days as comments roll in on the other repos and discussion page regarding upgrades/numpy support/etc., but all is ready for the transition here.

**Comment by liamhuber** [comment]
I don't want to drop testing for 3.8 until we drop _support_ for 3.8 on the other repos. At present the only thing I'm aware of holding this up is the conda environments at MPIE, but these should be resolved soon (some days) -- as soon as we get word that that transition is complete and have dropped official support for 3.8 on `pyiron_base`, `pyiron_atomistics`, etc., this can be merged.

**Comment by jan-janssen** [comment]
@liamhuber Can this be merged? As far as I understood @mbruns91 and @niklassiemer the CMTI cluster is now updated to Python 3.10 so I am not aware of any major system running pyiron which still uses Python 3.8. The major motivation to push this switch is that we have now issues like https://github.com/pyiron/pyiron_contrib/pull/800 which are the result of the backlog of updates we were not able to apply to `pyiron_contrib` as the corresponding packages dropped Python 3.8 like https://github.com/pyiron/pyiron_contrib/pull/762 and https://github.com/pyiron/pyiron_contrib/pull/780

**Comment by liamhuber** [comment]
> @liamhuber Can this be merged? As far as I understood @mbruns91 and @niklassiemer the CMTI cluster is now updated to Python 3.10 so I am not aware of any major system running pyiron which still uses Python 3.8. The major motivation to push this switch is that we have now issues like [pyiron/pyiron_contrib#800](https://github.com/pyiron/pyiron_contrib/pull/800) which are the result of the backlog of updates we were not able to apply to `pyiron_contrib` as the corresponding packages dropped Python 3.8 like [pyiron/pyiron_contrib#762](https://github.com/pyiron/pyiron_contrib/pull/762) and [pyiron/pyiron_contrib#780](https://github.com/pyiron/pyiron_contrib/pull/780)

Yes, but let's drop support for <3.9 before we drop tests for it. I just opened PRs to do this in
- [ ] [ironflow](https://github.com/pyiron/ironflow/pull/202)
- [ ] [pyiron_contrib](https://github.com/pyiron/pyiron_contrib/pull/802)
- [ ] [pyiron_module_template](https://github.com/pyiron/pyiron_module_template/pull/13)
- [ ] [pyiron_ontology](https://github.com/pyiron/pyiron_ontology/pull/23)

I'll let the CI run, but I don't expect any trouble and will merge them without review. Once they're finished I'm happy to merge here.

**Pull request merged**
