### PR TITLE
[Patch] Set the default runner to `ubuntu-22.04` and expose it as input everywhere

### PR DESCRIPTION
**Pull request by mbruns91**
I pick up [this one](https://github.com/pyiron/actions/pull/134)

### CODE REVIEW

**Comment by mbruns91** [comment]
`push-pull.yml`, `pyproject-release.yml` and `test-and-converage.yml` already exposed the runner.

**Comment by mbruns91** [comment]
shall we also set the default to `ubuntu-22.04` in this PR? From my perspective it make sense to define defaults that are compatible with the subsequent commands (e.g. `pip install ...`).

**Review by liamhuber — APPROVED** [review]
Yep, looks good to me.

It turns out I was likely wrong that this was an image bug and is rather a new "feature" of the latest ubuntu itself. I still like this as a short term patch while we get things rolling, but I opened a new issue (#136) to discuss a more long-term solution -- almost certainly one of the ideas you already proposed elsewhere.

**Comment by liamhuber** [comment]
Ah, @mbruns91, wait! It looks like `"ubuntu-latest"` will be rolled back to 22:

[Comment](https://github.com/actions/runner-images/issues/10636#issuecomment-2417303444):
> Hey everyone - thank you for your input. Based on community feedback we have decided to rollback the ubuntu-latest migration. All runs on ubuntu-latest will go back to Ubuntu-22 while we work out the issues with the image. We apologize for any service disruption you all may have had, and appreciate everyone’s feedback and patience. The rollback will be completed in the next hour.
> 
> To give some context for the changes we made - our images have become very large over the past 2 years and we were trying to free up some space to give us some breathing room going forward. There is currently no extra free space left for installing any more tooling, while still maintaining our free space SLA of 14gb. The size of the image also impacts performance of the VMs as well. Since a new OS is always a cutover, we took the opportunity to free up some space. Clearly this was not the right approach, and we apologize for the pain we have caused.
> 
> We will re-evaluate our communication and rollout strategy before beginning this migration again.

This PR should still go forward to expose the runner arg, but we can probably get away without updating the default image.

**Comment by mbruns91** [comment]
> Yep, it's rolled back to 22.04 already. Let's ditch the default change, but keep the runner exposure at input

I do not strongly object this, but personally I'd prefer to "properly" define the default runner. This makes it less ambiguous on what backend our CI tasks are running. 
From a (OS) support perspective, ubuntu 22.04 is totally fine for the next 4 years or so. So no realistic risk of using outdated stuff. But more importantly, we will avoid similar issues in the future. When we want to upgrade the runner image being used as default, it will be much easier by testing on a selected repository - via the exposed `runner` input - before rolling it out as a new default.

**Pull request merged**
