### PR TITLE
Use Coveralls Github action

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by liamhuber** [comment]
Awesome, thanks! Today I'll point one of the repos to this commit to make sure it's working as intended, then merge as long as everything works as expected.

**Comment by jan-janssen** [comment]
> Awesome, thanks! Today I'll point one of the repos to this commit to make sure it's working as intended, then merge as long as everything works as expected.

Is it possible to have unit tests for this repository? So we can see if changes to the `actions` have the correct effects.

**Comment by liamhuber** [comment]
> > Awesome, thanks! Today I'll point one of the repos to this commit to make sure it's working as intended, then merge as long as everything works as expected.
> 
> Is it possible to have unit tests for this repository? So we can see if changes to the `actions` have the correct effects.

Probably? But I'm not sure. Somethings for sure would be hard to test that way, as the intent is to use these as reusable workflows, but github forces us to store them in `.github/workflows` so I don't know what the interaction would be between writing the workflows and having them run on the repo holding them.

I like the idea, I think it has a high probability of working, but I don't have the time to prioritize experimenting with it right now.

**Comment by liamhuber** [comment]
Beautiful, worked perfectly [over on pyiron_ontology](https://github.com/pyiron/pyiron_ontology/pull/28).

I poked in and it's definitely running the new command too:
Screen Shot 2023-10-11 at 11 37 21

**Pull request merged**
